volumes:
    LocalSettings:
        driver: local
    images:
        driver: local
    skins:
        driver: local
    extensions:
        driver: local
    db:
        driver: local
    initdb:
        driver: local

networks:
  REVERSE_PROXY:
    external: true
  net:
     driver: bridge
     ipam:
        driver: default
        config:
          - subnet: ${PROJECT_SUBNET:-192.168.8.224/28} #(8.201-8.206, 207)
     driver_opts:
       com.docker.network.bridge.name: mw_net

services:
    mw.db:
        image: 'mariadb:${MARIADB_VERSION:-lts}'
        container_name: mw.db
        hostname: db
        restart: always
        networks:
          - net
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: no
            MARIADB_RANDOM_ROOT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD:-yes}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            TZ: 'Europe/Amsterdam'
        volumes:
          - db:/var/lib/mysql
          - initdb:/docker-entrypoint-initdb.d

    mw.php:
        hostname: mw.php
        container_name: mw.php
        restart: always
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network=REVERSE_PROXY"
          - "traefik.http.routers.${PROJECT}.rule=Host(`${PROJECT_FQDN}`)"
          - "traefik.http.routers.${PROJECT}.entrypoints=${PROJECT_ENTRYPOINT}"
          - "traefik.http.routers.${PROJECT}.tls.domains[0].main=${PROJECT_DOMAIN_MAIN}"
          - "traefik.http.routers.${PROJECT}.tls.domains[0].sans=${PROJECT_DOMAIN_SANS}"
          - "traefik.http.routers.${PROJECT}.tls.certresolver=${PROJECT_CERT_RESOLVER}"
          - "traefik.http.services.${PROJECT}.loadbalancer.server.port=80"
        networks:
          - REVERSE_PROXY
          - net
        image: ghcr.io/vslcatena/docker-mediawiki:${MW_VERSION:-lts}
        pull_policy: always
        build:
            dockerfile: Dockerfile
            context: ./src
            args:
                VERSION: ${MW_VERSION:-lts}
                UID: 1000
                GID: 1000
        depends_on:
            - mw.db
        environment:
           MW_WGDEBUGMODE: '${MW_WGDEBUGMODE}'
           MW_WGDBSERVER: '${MARIADB_HOST:-db}'
           MW_WGDBNAME: '${MARIADB_DATABASE:-wiki}'
           MW_WGDBUSER: '${MARIADB_USER:-wikiuser}'
           MW_WGDBPASSWORD: '${MARIADB_PASSWORD:-password}'          
           MW_WGDBPREFIX: '${MW_WGDBPREFIX}'
           MW_WGDBSSL: '${MW_WGDBSSL:-false}'
           MW_WGDBTABLEOPTIONS: '${MW_WGDBTABLEOPTIONS}'
           MW_WGDBTYPE: '${MW_WGDBTYPE}'
           MW_WGSHAREDTABLES: '${MW_WGSHAREDTABLES}'
           PHP_LOG_ERRORS: '${PHP_LOG_ERRORS:-Off}'
           PHP_ERROR_REPORTING: '${PHP_ERROR_REPORTING:-E_ALL & ~E_DEPRECATED & ~E_STRICT}'
           TZ: '${TZ:-Europe/Amsterdam}'
           MW_WGSERVER: '${MW_WGSERVER}'
           MW_WGSITENAME: '${MW_WGSITENAME}'
           MW_WGMETANAMESPACE: '${MW_WGMETANAMESPACE}'
           MW_WGAUTHENTICATIONTOKENVERSION: '${MW_WGAUTHENTICATIONTOKENVERSION:-"1"}'
           MW_WGSECRETKEY: '${MW_WGSECRETKEY}'
           MW_WGUPGRADEKEY: '${MW_WGUPGRADEKEY}'
           MW_WGDEFAULTSKIN: '${MW_WGDEFAULTSKIN}'
           MW_WGDIFF3: '${MW_WGDIFF3}'
           MW_WGEMAILAUTHENTICATION: '${MW_WGEMAILAUTHENTICATION:-false}'
           MW_WGEMERGENCYCONTACT: '${MW_WGEMERGENCYCONTACT}'
           MW_WGENABLEEMAIL: '${MW_WGENABLEEMAIL:-false}'
           MW_WGENABLEUPLOADS: '${MW_WGENABLEUPLOADS:-false}'
           MW_WGENABLEUSEREMAIL: '${MW_WGENABLEUSEREMAIL:-false}'
           MW_WGENOTIFUSERTALK: '${MW_WGENOTIFUSERTALK:-false}'
           MW_WGENOTIFWATCHLIST: '${MW_WGENOTIFWATCHLIST:-false}'
           MW_WGIMAGEMAGICKCONVERTCOMMAND: '${MW_WGIMAGEMAGICKCONVERTCOMMAND}'
           MW_WGLANGUAGECODE: '${MW_WGLANGUAGECODE}'
           MW_WGLOCALTIMEZONE: '${MW_WGLOCALTIMEZONE}'
           MW_WGMAINCACHETYPE: '${MW_WGMAINCACHETYPE}'
           MW_WGMEMCACHEDSERVERS: '${MW_WGMEMCACHEDSERVERS}'
           MW_WGPASSWORDSENDER: '${MW_WGPASSWORDSENDER}'
           MW_WGPINGBACK: '${MW_WGPINGBACK}'
           MW_WGRESOURCEBASEPATH: '${MW_WGRESOURCEBASEPATH}'
           MW_WGRIGHTSICON: '${MW_WGRIGHTSICON}'
           MW_WGRIGHTSPAGE: '${MW_WGRIGHTSPAGE}'
           MW_WGRIGHTSTEXT: '${MW_WGRIGHTSTEXT}'
           MW_WGRIGHTSURL: '${MW_WGRIGHTSURL}'
           MW_WGSAFEIPS: '${MW_WGSAFEIPS:-"localhost,127.0.0.1"}'
           MW_WGSCRIPTPATH: '${MW_WGSCRIPTPATH}'
           MW_WGUSEIMAGEMAGICK: '${MW_WGUSEIMAGEMAGICK:-true}'
           MW_WGUSEINSTANTCOMMONS: '${MW_WGUSEINSTANTCOMMONS:-true}'
        volumes:
            - LocalSettings:/var/www/html/conf.d
            - images:/var/www/html/images
            - skins:/var/www/html/skins
            - extensions:/var/www/html/extensions
