volumes:
    LocalSettings:
        driver: local
    images:
        driver: local
    skins:
        driver: local
    extensions:
        driver: local
    db:
        driver: local
    initdb:
        driver: local

networks:
  REVERSE_PROXY:
    external: true
  net:
     driver: bridge
     ipam:
        driver: default
        config:
          - subnet: ${PROJECT_SUBNET:-192.168.8.224/28} #(8.201-8.206, 207)
     driver_opts:
       com.docker.network.bridge.name: mw_net

services:
    mw.db:
        image: 'mariadb:${MARIADB_VERSION:-lts}'
        container_name: mw.db
        hostname: db
        restart: always
        networks:
          - net
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: no
            MARIADB_RANDOM_ROOT_PASSWORD: ${MARIADB_RANDOM_ROOT_PASSWORD:-yes}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            TZ: 'Europe/Amsterdam'
        volumes:
          - db:/var/lib/mysql
          - initdb:/docker-entrypoint-initdb.d

    mw.php:
        hostname: mw.php
        container_name: mw.php
        restart: always
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network=REVERSE_PROXY"
          - "traefik.http.routers.${PROJECT}.rule=Host(`${PROJECT_FQDN}`)"
          - "traefik.http.routers.${PROJECT}.entrypoints=${PROJECT_ENTRYPOINT}"
          - "traefik.http.routers.${PROJECT}.tls.domains[0].main=${PROJECT_DOMAIN_MAIN}"
          - "traefik.http.routers.${PROJECT}.tls.domains[0].sans=${PROJECT_DOMAIN_SANS}"
          - "traefik.http.routers.${PROJECT}.tls.certresolver=${PROJECT_CERT_RESOLVER}"
          - "traefik.http.services.${PROJECT}.loadbalancer.server.port=80"
        networks:
          - REVERSE_PROXY
          - net
        ports:
          - ${MW_HOSTPORT:-127.0.0.1:8100}:80
        image: ghcr.io/vslcatena/docker-mediawiki:${MW_VERSION:-lts}
        pull_policy: always
        build:
            dockerfile: Dockerfile
            context: ./src
            args:
                VERSION: ${MW_VERSION:-lts}
                UID: 1000
                GID: 1000
        depends_on:
            - mw.db
        environment:
           MW_SITE_SERVER: '${MW_SITE_SERVER}'
           MW_DB_NAME: '${MARIADB_DATABASE:-wiki}'
           MW_DB_USER: '${MARIADB_USER:-wikiuser}'
           MW_DB_PASS: '${MARIADB_PASSWORD:-password}'
           PHP_LOG_ERRORS: '${PHP_LOG_ERRORS:-Off}'
           PHP_ERROR_REPORTING: '${PHP_ERROR_REPORTING:-E_ALL & ~E_DEPRECATED & ~E_STRICT}'
           TZ: '${TZ:-Europe/Amsterdam}'
        volumes:
            - LocalSettings:/var/www/html/conf.d
            - images:/var/www/html/images
            - skins:/var/www/html/skins
            - extensions:/var/www/html/extensions
